### ISSUE TITLE
Unable to use normally

### ISSUE THREAD

**Issue by G-LJDS2022** [juzeon/SydneyQt-browser-extension#2] opened 2024-02-02 00:51 UTC
![1706834800271](https://github.com/juzeon/SydneyQt-browser-extension/assets/134282368/35580de2-7732-4b0a-ac1c-f343276d86d5)

**Comment by juzeon** [comment] 2024-02-03 02:36
Duplicate of #1

**Closed as completed by juzeon** 2024-02-03 02:36 UTC
